# Generated by Django 4.1.7 on 2023-02-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='work_type',
            field=models.CharField(choices=[('YOUTBE', 'YOUTUBE'), ('INSTAG', 'INSTAGRAM'), ('OTHER', 'OTHER')], max_length=8),
        ),
    ]
